FROM python:3.10-alpine

# Create the app directory
RUN mkdir /app

# Set the working directory inside the container
WORKDIR /app


# Set environment variables 
# Prevents Python from writing pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
#Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1 

# Upgrade pip
RUN pip install --upgrade pip 

# Only copy requirements.txt first
COPY requirements.txt .

# Install dependencies first (caching layer)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project to the container
COPY . /app/

# Expose the Django port
EXPOSE 8000

